// Schema of the static JSON files in src/data (generated by scripts/build-data.ts).

export interface UnitBase {
  /** Stable code, unique within its own system (old or new). */
  code: string;
  /** Display name with full Vietnamese diacritics, e.g. "Phường Thanh Khê". */
  name: string;
  /** Accent-stripped lowercase name for search, e.g. "phuong thanh khe". */
  nameNormalized: string;
}

export type OldWard = UnitBase;

export interface OldDistrict extends UnitBase {
  wards: OldWard[];
}

export interface OldProvince extends UnitBase {
  districts: OldDistrict[];
}

export interface OldUnitsFile {
  provinces: OldProvince[];
}

export type NewWard = UnitBase;

export interface NewProvince extends UnitBase {
  wards: NewWard[];
}

export interface NewUnitsFile {
  provinces: NewProvince[];
}

export interface MappingRecord {
  oldWardCode: string;
  newWardCode: string;
  note?: string;
}

// Converter results

export interface OldUnitRef {
  wardCode: string;
  wardName: string;
  districtName: string;
  provinceName: string;
  fullAddress: string;
}

export interface NewUnitRef {
  wardCode: string;
  wardName: string;
  provinceName: string;
  fullAddress: string;
  note?: string;
}

export interface OldToNewResult {
  from: OldUnitRef;
  /** All new wards the old ward was assigned to (1 item when unambiguous). */
  matches: NewUnitRef[];
  /** True when the old ward was split into multiple new wards. */
  isAmbiguous: boolean;
}

export interface NewToOldResult {
  from: NewUnitRef;
  /** Every old ward that was merged into the new ward — always the full list. */
  sources: OldUnitRef[];
}
