/**
 * Two-way converter between old (63-province) and new (34-province)
 * administrative units. Server-only: loads the static JSON data
 * generated by scripts/build-data.ts and builds in-memory indexes once.
 */
import mappingJson from "@/data/mapping.json";
import newUnitsJson from "@/data/new-units.json";
import oldUnitsJson from "@/data/old-units.json";

import type {
  MappingRecord,
  NewProvince,
  NewToOldResult,
  NewUnitsFile,
  NewUnitRef,
  NewWard,
  OldDistrict,
  OldProvince,
  OldToNewResult,
  OldUnitsFile,
  OldUnitRef,
  OldWard,
} from "./address-types";

const oldUnits = oldUnitsJson as OldUnitsFile;
const newUnits = newUnitsJson as NewUnitsFile;
const mapping = mappingJson as MappingRecord[];

interface OldWardEntry {
  ward: OldWard;
  district: OldDistrict;
  province: OldProvince;
}

interface NewWardEntry {
  ward: NewWard;
  province: NewProvince;
}

const oldWardIndex = new Map<string, OldWardEntry>();
for (const province of oldUnits.provinces) {
  for (const district of province.districts) {
    for (const ward of district.wards) {
      oldWardIndex.set(ward.code, { ward, district, province });
    }
  }
}

const newWardIndex = new Map<string, NewWardEntry>();
for (const province of newUnits.provinces) {
  for (const ward of province.wards) {
    newWardIndex.set(ward.code, { ward, province });
  }
}

const oldToNew = new Map<string, MappingRecord[]>();
const newToOld = new Map<string, MappingRecord[]>();
for (const record of mapping) {
  const forward = oldToNew.get(record.oldWardCode);
  if (forward) forward.push(record);
  else oldToNew.set(record.oldWardCode, [record]);
  const backward = newToOld.get(record.newWardCode);
  if (backward) backward.push(record);
  else newToOld.set(record.newWardCode, [record]);
}

function toOldRef({ ward, district, province }: OldWardEntry): OldUnitRef {
  // Synthetic ward of an island district shares the district's name;
  // don't repeat it in the address.
  const fullAddress =
    ward.name === district.name
      ? `${district.name}, ${province.name}`
      : `${ward.name}, ${district.name}, ${province.name}`;
  return {
    wardCode: ward.code,
    wardName: ward.name,
    districtName: district.name,
    provinceName: province.name,
    fullAddress,
  };
}

function toNewRef({ ward, province }: NewWardEntry, note?: string): NewUnitRef {
  return {
    wardCode: ward.code,
    wardName: ward.name,
    provinceName: province.name,
    fullAddress: `${ward.name}, ${province.name}`,
    ...(note ? { note } : {}),
  };
}

/**
 * Old → new. Returns every new ward the old ward was assigned to
 * (`isAmbiguous` when it was split into several), or null if the
 * old ward code is unknown.
 */
export function convertOldToNew(oldWardCode: string): OldToNewResult | null {
  const entry = oldWardIndex.get(oldWardCode);
  if (!entry) return null;
  const records = oldToNew.get(oldWardCode) ?? [];
  const matches = records.flatMap((r) => {
    const target = newWardIndex.get(r.newWardCode);
    return target ? [toNewRef(target, r.note)] : [];
  });
  return { from: toOldRef(entry), matches, isAmbiguous: matches.length > 1 };
}

/**
 * New → old. Returns the full list of old wards that were merged into
 * the new ward, or null if the new ward code is unknown.
 */
export function convertNewToOld(newWardCode: string): NewToOldResult | null {
  const entry = newWardIndex.get(newWardCode);
  if (!entry) return null;
  const records = newToOld.get(newWardCode) ?? [];
  const sources = records.flatMap((r) => {
    const source = oldWardIndex.get(r.oldWardCode);
    return source ? [toOldRef(source)] : [];
  });
  return { from: toNewRef(entry), sources };
}

/** Province lists for the UI (codes + names only, no ward payload). */
export function getOldProvinceOptions() {
  return oldUnits.provinces.map(({ code, name, nameNormalized }) => ({
    code,
    name,
    nameNormalized,
  }));
}

export function getNewProvinceOptions() {
  return newUnits.provinces.map(({ code, name, nameNormalized }) => ({
    code,
    name,
    nameNormalized,
  }));
}

/** Districts + wards of one old province (payload for the cascade UI). */
export function getOldProvince(code: string): OldProvince | null {
  return oldUnits.provinces.find((p) => p.code === code) ?? null;
}

/** Wards of one new province. */
export function getNewProvince(code: string): NewProvince | null {
  return newUnits.provinces.find((p) => p.code === code) ?? null;
}
