/**
 * Two-way converter between old (63-province) and new (34-province)
 * administrative units. Server-only: loads the static JSON data
 * generated by scripts/build-data.ts and builds in-memory indexes once.
 */
import hamletsJson from "@/data/hamlets.json";
import mappingJson from "@/data/mapping.json";
import newUnitsJson from "@/data/new-units.json";
import newWardHamletsJson from "@/data/new-ward-hamlets.json";
import oldUnitsJson from "@/data/old-units.json";

import { normalizeVietnamese } from "./normalize";
import type {
  HamletRecord,
  MappingRecord,
  WardHamlets,
  NewProvince,
  NewToOldResult,
  NewUnitsFile,
  NewUnitRef,
  NewWard,
  NewWardHamlet,
  NewWardHamlets,
  OldDistrict,
  OldProvince,
  OldToNewResult,
  OldUnitsFile,
  OldUnitRef,
  OldWard,
  TransferKind,
} from "./address-types";

const oldUnits = oldUnitsJson as OldUnitsFile;
const newUnits = newUnitsJson as NewUnitsFile;
const mapping = mappingJson as MappingRecord[];
const hamletsByOldWard = new Map(
  (hamletsJson as WardHamlets[]).map((h) => [
    h.oldWardCode,
    {
      source: h.source,
      hamlets: h.hamlets.map(
        (x): HamletRecord => ({
          ...x,
          nameNormalized: normalizeVietnamese(x.name),
        }),
      ),
    },
  ]),
);
// new→old: precompute normalized names once for the searchable combobox.
const hamletsByNewWard = new Map(
  (newWardHamletsJson as NewWardHamlets[]).map((h) => [
    h.newWardCode,
    {
      source: h.source,
      hamlets: h.hamlets.map(
        (x): NewWardHamlet => ({
          ...x,
          nameNormalized: normalizeVietnamese(x.name),
        }),
      ),
    },
  ]),
);

interface OldWardEntry {
  ward: OldWard;
  district: OldDistrict;
  province: OldProvince;
}

interface NewWardEntry {
  ward: NewWard;
  province: NewProvince;
}

const oldWardIndex = new Map<string, OldWardEntry>();
for (const province of oldUnits.provinces) {
  for (const district of province.districts) {
    for (const ward of district.wards) {
      oldWardIndex.set(ward.code, { ward, district, province });
    }
  }
}

const newWardIndex = new Map<string, NewWardEntry>();
for (const province of newUnits.provinces) {
  for (const ward of province.wards) {
    newWardIndex.set(ward.code, { ward, province });
  }
}

const oldToNew = new Map<string, MappingRecord[]>();
const newToOld = new Map<string, MappingRecord[]>();
for (const record of mapping) {
  const forward = oldToNew.get(record.oldWardCode);
  if (forward) forward.push(record);
  else oldToNew.set(record.oldWardCode, [record]);
  const backward = newToOld.get(record.newWardCode);
  if (backward) backward.push(record);
  else newToOld.set(record.newWardCode, [record]);
}

function toOldRef(
  { ward, district, province }: OldWardEntry,
  transfer?: TransferKind,
): OldUnitRef {
  // Synthetic ward of an island district shares the district's name;
  // don't repeat it in the address.
  const fullAddress =
    ward.name === district.name
      ? `${district.name}, ${province.name}`
      : `${ward.name}, ${district.name}, ${province.name}`;
  return {
    wardCode: ward.code,
    wardName: ward.name,
    districtName: district.name,
    provinceName: province.name,
    fullAddress,
    ...(transfer ? { transfer } : {}),
  };
}

function toNewRef(
  { ward, province }: NewWardEntry,
  note?: string,
  transfer?: TransferKind,
): NewUnitRef {
  return {
    wardCode: ward.code,
    wardName: ward.name,
    provinceName: province.name,
    fullAddress: `${ward.name}, ${province.name}`,
    ...(note ? { note } : {}),
    ...(transfer ? { transfer } : {}),
  };
}

/**
 * Old → new. Returns every new ward the old ward was assigned to
 * (`isAmbiguous` when it was split into several), or null if the
 * old ward code is unknown.
 */
export function convertOldToNew(oldWardCode: string): OldToNewResult | null {
  const entry = oldWardIndex.get(oldWardCode);
  if (!entry) return null;
  const records = oldToNew.get(oldWardCode) ?? [];
  const matches = records.flatMap((r) => {
    const target = newWardIndex.get(r.newWardCode);
    return target ? [toNewRef(target, r.note, r.transfer)] : [];
  });
  const isAmbiguous = matches.length > 1;
  // Hamlet list is offered whenever the source has it — as a precise picker
  // for split wards, and just to complete the address for unsplit ones.
  const wardHamlets = hamletsByOldWard.get(oldWardCode);
  return {
    from: toOldRef(entry),
    matches,
    isAmbiguous,
    ...(wardHamlets
      ? { hamlets: wardHamlets.hamlets, hamletSource: wardHamlets.source }
      : {}),
  };
}

/**
 * New → old. Returns the full list of old wards that were merged into
 * the new ward, or null if the new ward code is unknown.
 */
export function convertNewToOld(newWardCode: string): NewToOldResult | null {
  const entry = newWardIndex.get(newWardCode);
  if (!entry) return null;
  const records = newToOld.get(newWardCode) ?? [];
  const sources = records.flatMap((r) => {
    const source = oldWardIndex.get(r.oldWardCode);
    if (!source) return [];
    const ref = toOldRef(source, r.transfer);
    const names = hamletsByOldWard
      .get(r.oldWardCode)
      ?.hamlets.filter((h) => h.newWardCode === newWardCode)
      .map((h) => h.name);
    if (names && names.length > 0) ref.hamletNames = names;
    return [ref];
  });
  const wardHamlets = hamletsByNewWard.get(newWardCode);
  return {
    from: toNewRef(entry),
    sources,
    ...(wardHamlets
      ? { hamlets: wardHamlets.hamlets, hamletSource: wardHamlets.source }
      : {}),
  };
}

/** Province lists for the UI (codes + names only, no ward payload). */
export function getOldProvinceOptions() {
  return oldUnits.provinces.map(({ code, name, nameNormalized }) => ({
    code,
    name,
    nameNormalized,
  }));
}

export function getNewProvinceOptions() {
  return newUnits.provinces.map(({ code, name, nameNormalized }) => ({
    code,
    name,
    nameNormalized,
  }));
}

/** Districts + wards of one old province (payload for the cascade UI). */
export function getOldProvince(code: string): OldProvince | null {
  return oldUnits.provinces.find((p) => p.code === code) ?? null;
}

/** Wards of one new province. */
export function getNewProvince(code: string): NewProvince | null {
  return newUnits.provinces.find((p) => p.code === code) ?? null;
}
